In [1]:
import numpy as np
import matplotlib.pyplot as plt
from numpy.polynomial import Polynomial


def matrice(X,p):
    n = len(X)
    A = np.zeros((n, p+1))
    for i in range (n):
        for j in range (p+1):
            A[i,j]=X[i]**j
    return A

In [14]:
def matrice(X, p):
    return np.vander(X, p+1, increasing=True)

In [15]:
X = np.array([-1, 1, 0])
Y=np.array([1,2,3])
p=3
print(matrice(Y,p)) 
print(matrice(X, p))

[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]]
[[ 1 -1  1 -1]
 [ 1  1  1  1]
 [ 1  0  0  0]]


In [25]:
import numpy as np

def regression(X, Y, p):
    A = np.vander(X, p+1, increasing=True)
    # REMPLACEZ la ligne suivante :
    Lambd = np.linalg.pinv(A) @ Y  # ← UTILISEZ CELLE-CI
    return Lambd

In [28]:
# Testons avec vos données
X = np.array([0, 1, 2, 3, 4, 5])
Y = np.array([1, 1.5, 2.5, 3.5, 5.0, 7.0])
p = 3

Lambda = regression(X, Y, p)
print(Lambda)


[0.97619048 0.52777778 0.06547619 0.01388889]
